In [1]:
import numpy as np

In [5]:
#1. Create a null vector of size 10 but the fifth value which is 1.
a=np.zeros(10).astype('int')
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [8]:
#2. Create a vector with values ranging from 10 to 49.
b=np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
c=np.random.randint(0,8,(3,3))
c

array([[2, 1, 3],
       [7, 5, 2],
       [0, 1, 4]])

In [16]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
d=np.array([1,2,0,0,4,0])
d.nonzero()


(array([0, 1, 4], dtype=int64),)

In [31]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
np.random.seed(5)
e=np.random.randn(10,10)
print('Matrix',e,'\n','Minmum : ',e.min(),'\n','Maximum : ',e.max())

Matrix [[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984  1.58248112
  -0.9092324  -0.59163666  0.18760323 -0.32986996]
 [-1.19276461 -0.20487651 -0.35882895  0.6034716  -1.66478853 -0.70017904
   1.15139101  1.85733101 -1.51117956  0.64484751]
 [-0.98060789 -0.85685315 -0.87187918 -0.42250793  0.99643983  0.71242127
   0.05914424 -0.36331088  0.00328884 -0.10593044]
 [ 0.79305332 -0.63157163 -0.00619491 -0.10106761 -0.05230815  0.24921766
   0.19766009  1.33484857 -0.08687561  1.56153229]
 [-0.30585302 -0.47773142  0.10073819  0.35543847  0.26961241  1.29196338
   1.13934298  0.4944404  -0.33633626 -0.10061435]
 [ 1.41339802  0.22125412 -1.31077313 -0.68956523 -0.57751323  1.15220477
  -0.10716398  2.26010677  0.65661947  0.12480683]
 [-0.43570392  0.97217931 -0.24071114 -0.82412345  0.56813272  0.01275832
   1.18906073 -0.07359332 -2.85968797  0.7893664 ]
 [-1.87774088  1.53875615  1.82136474 -0.42703139 -1.16470191 -1.39707402
   0.87265462 -0.20211818 -0.59835993 -0.243

In [33]:
#6. Create a random vector of size 30 and find the mean value.
f=np.random.randint(1,10,(5,6))
print('mean values is %.3f'%f.mean())

mean values is 5.233
